# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b53e98c1a7a5661eec4a65d898c1d784c09d6e08297e0b9cdff005ba99702afbc6196b405c5e0a40f24147a525ab04a29ced43d828660afc7974d1bed0633c4

test:
  secret_key_base: ff8b527f7b5e21d181d8ba57c5f39d0b2c75cd5d76da5ee744d343853265f33a9f8825b018908f3f19611c5c6ceb79f20146d29f87fcb89bb6dd886d7bdcf358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
